### ISSUE TITLE
Spider bed not working

### ISSUE THREAD

**Issue by yurinotdead** [WildBamaBoy/spider-queen#171]
When i try to sleep in the spider bed in the day it does nothing but during the night it says: "You can only sleep during the day"

**Comment by Biblop** [comment]
Yeah, this problem is happening to me too. I'm using the 1.7.10 version and the java 7u71, radix-core is the 1.3.3, but it says that 1.3.4 was released (only compatible with java 6). Luckily, the problem here, when solved, gonna sane the one in #181 .
Thanks!
