### ISSUE TITLE
Webslinger Bug

### ISSUE THREAD

**Issue by Khaamat** [WildBamaBoy/spider-queen#181]
Just a few moments ago I tried to using the web slinger and it "got stuck". I had this bug once, when I was trying to pull a cocoon. The webslinger "head" become stuck in a block and I cant use it. Even destroying the block, throwing it away and getting it back didnt "unstuck" it, but this time after some seconds of waiting it went back to normal. 
![captura de tela 2014-11-07 02 47 09](https://cloud.githubusercontent.com/assets/8165677/4948588/7a72f33c-6628-11e4-8618-1fbf46a11e80.png)

**Comment by Biblop** [comment]
Same problem here. Using the 1.7.10 version plus the Orespawn mod. Pehaps this problem is the same in #186. 

Thanks!
