### ISSUE TITLE
WebSling not working

### ISSUE THREAD

**Issue by BiancaRoughFin** [WildBamaBoy/spider-queen#186]
I recently updated my Minecraft to 1.7.10 to use the corresponding version of Spiderqueen and for some reason the WebSling isnt working anymore. It shots the white web orb at the target location or mob but doesnt allow me to climb/swing or pull the target closer. The line that was suppost to go from my char to the orb doesnt show and the orb remains where it landed for about a minute before vanishing and the Websling is unusable during that time.

**Comment by RenegadeElement** [comment]
I have the same issue, confirmed.
