### ISSUE TITLE
(Suggestions) Spider Abilities/New Spiders?

### ISSUE THREAD

**Issue by Phantomshade1712** [WildBamaBoy/spider-queen#197]
A few ideas, some of which go along with a few other people have made.

1. your attack slowly goes goes up as you gain level's. That way you don’t have to use weapons to fight as much.

Bite attacks that poison a target with of different kinds that you can switch between. Also effected by levels(Maybe and RPG GUI that lets you level up your abilities.)

2. Web platforms that you can stand on, so you can make webs in the jungle to use as your Spider Queen or King base. But being able to go through it if you press a key like C or something so you can come down on top of some unsuspecting prey, like Spiders do in the movies.

3. Larger types of spiders, like large versions of normal ones or new types of spiders all together. You might have to add mobs that you can web and use as hosts for them.

4. New Spider Species?

5. More Spider Queen skins. I really want to see more Spider King type skins as well as more unique Spider Queen Skins.

**Comment by Etheralslayer** [comment]
yas
