### ISSUE TITLE
[Compatibility: Optifine] Player Skin only

### ISSUE THREAD

**Issue by SimonDKiller** [WildBamaBoy/spider-queen#200]
Ok, i explain my problem:

I start to create a private personal modpack and i found some mods to this. But, when i try to add the mod Optifine (i think one of the most used), my skin are my skin from the Minecraft's servers.

OptiFine_1.7.10_HD_U_B5
SpiderQueenReborn-1.7.10-1.2.2-universal
RadixCore-1.7.x-1.3.3-universal

http://img.imagesia.com/fichiers/v9/2015-03-06-11-04-28_imagesia-com_v91k.png
http://img.imagesia.com/fichiers/v9/2015-03-06-11-06-50_imagesia-com_v91l.png

**Comment by typervader** [comment]
I was having a similir issue. I also made a Modpack with spiderqueen, and the skin seemed to dissapper when I had any other mod other then it and too many items on. It might have just been optfine however. Probly is a compatiblity problem we have to work without for now.

**Comment by arula555** [comment]
I recomend you to update optifine to newest version B6
