### ISSUE TITLE
Friendly Creepers explosion mechanics

### ISSUE THREAD

**Issue by lagoman** [WildBamaBoy/spider-queen#234]
Friendly creeper explosions should not destroy the creeper, but leave the Creeper "tired" (texture change to indicate this)
Feeding it a gundpowder recharges it.

**Comment by lagoman** [comment]
Right click with flint and steel (fire item) to trigger an explosion.
This gives you a walking bomb that can be recharged and triggered as you desire.

**Comment by WildBamaBoy** [comment]
Friendly creepers give gunpowder when given a heart - would be easy to abuse this feature. Any alternatives?

**Comment by WildBamaBoy** [comment]
In retrospect it may level out since hearts are rare and killing other creepers would break any allegiance.
