### ISSUE TITLE
[Issue] Spider Rod not Placing Correctly

### ISSUE THREAD

**Issue by FrozenPulse** [WildBamaBoy/spider-queen#240]
Placing a Spider Rod on top of tall grass (the 1-block height kind) causes the rod to disappear from the player's inventory without being placed down. The same issue occurs if you try to place the rod down on the sides of blocks (this issue occurred when trying to place it on the side of a grass block, onto another grass block).

This issue occurred in survival, and not in creative. I can provide a list of currently-used mods if you need it. The current version I am using is Spider Queen V1.0.1.

**Comment by WildBamaBoy** [comment]
Fixed in 8db7317905e69229fbe92df8991888f73daa55a1
